language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
# command to install dependencies
# command to run tests
script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]] ; then make test-readme; fi
cache: pip
jobs:
  include:
    - stage: test
      script:
        - |
          if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]] ; then make test-readme; fi
    - stage: coverage
      python: 3.6
      script: codecov

